import type { CatalogFoodSeed } from '@/application/ports';

export const USDA_FOUNDATION_CATALOG_KEY = 'usda-foundation';
export const USDA_FOUNDATION_CATALOG_VERSION = '2026-04-30';

/** Nutrition is sourced from USDA Foundation Foods per 100 g. Presentation is local editorial metadata. */
export const USDA_FOUNDATION_CATALOG: readonly CatalogFoodSeed[] = [
  {
    fdcId: 2646170,
    usdaDescription: 'Chicken, breast, boneless, skinless, raw',
    per100g: {
      calories: 106,
      proteinG: 22.5,
      carbsG: 0,
      fatG: 1.93,
      fiberG: 0,
      sodiumMg: 65.8,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Chicken breast',
      es: 'Pechuga de pollo',
      aliases: ['Chicken breast', 'Pechuga de pollo', 'chicken', 'pollo', 'pechuga'],
    },
  },
  {
    fdcId: 331960,
    usdaDescription:
      'Chicken, broiler or fryers, breast, skinless, boneless, meat only, cooked, braised',
    per100g: {
      calories: 166,
      proteinG: 32.1,
      carbsG: 0,
      fatG: 3.24,
      fiberG: 0,
      sodiumMg: 47,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Cooked chicken breast',
      es: 'Pechuga de pollo cocida',
      aliases: [
        'Cooked chicken breast',
        'Pechuga de pollo cocida',
        'cooked chicken',
        'pollo cocido',
      ],
    },
  },
  {
    fdcId: 2646175,
    usdaDescription: 'Beef, flank, steak, boneless, choice, raw',
    per100g: {
      calories: 164,
      proteinG: 20.1,
      carbsG: 0,
      fatG: 9.4,
      fiberG: 0,
      sodiumMg: 51.3,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Beef flank steak',
      es: 'Bife de vacío',
      aliases: ['Beef flank steak', 'Bife de vacío', 'flank steak', 'carne vacuna', 'vacio'],
    },
  },
  {
    fdcId: 2514743,
    usdaDescription: 'Beef, ground, 90% lean meat / 10% fat, raw',
    per100g: {
      calories: 185,
      proteinG: 18.2,
      carbsG: 0,
      fatG: 12.8,
      fiberG: 0,
      sodiumMg: 61.6,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Lean ground beef',
      es: 'Carne picada magra',
      aliases: [
        'Lean ground beef',
        'Carne picada magra',
        'ground beef',
        'carne molida',
        'carne picada',
      ],
    },
  },
  {
    fdcId: 2684441,
    usdaDescription: 'Fish, salmon, Atlantic, farm raised, raw',
    per100g: {
      calories: 197,
      proteinG: 20.3,
      carbsG: 0,
      fatG: 13.1,
      fiberG: 0,
      sodiumMg: 49.5,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Atlantic salmon',
      es: 'Salmón atlántico',
      aliases: ['Atlantic salmon', 'Salmón atlántico', 'salmon'],
    },
  },
  {
    fdcId: 334194,
    usdaDescription: 'Fish, tuna, light, canned in water, drained solids',
    per100g: {
      calories: 90,
      proteinG: 19,
      carbsG: 0.08,
      fatG: 0.94,
      fiberG: 0,
      sodiumMg: 219,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Canned light tuna',
      es: 'Atún al agua',
      aliases: ['Canned light tuna', 'Atún al agua', 'tuna', 'atun'],
    },
  },
  {
    fdcId: 323604,
    usdaDescription: 'Egg, whole, raw, frozen, pasteurized',
    per100g: {
      calories: 150,
      proteinG: 12.3,
      carbsG: 0.91,
      fatG: 10.3,
      fiberG: 0,
      sodiumMg: 121,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Whole egg',
      es: 'Huevo entero',
      aliases: ['Whole egg', 'Huevo entero', 'egg', 'huevo'],
    },
  },
  {
    fdcId: 330137,
    usdaDescription: 'Yogurt, Greek, plain, nonfat',
    per100g: {
      calories: 61,
      proteinG: 10.3,
      carbsG: 3.64,
      fatG: 0.37,
      fiberG: 0,
      sodiumMg: 36,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Nonfat Greek yogurt',
      es: 'Yogur griego descremado',
      aliases: ['Nonfat Greek yogurt', 'Yogur griego descremado', 'greek yogurt', 'yogur griego'],
    },
  },
  {
    fdcId: 2259793,
    usdaDescription: 'Yogurt, plain, whole milk',
    per100g: {
      calories: 78,
      proteinG: 3.82,
      carbsG: 5.57,
      fatG: 4.48,
      fiberG: 0,
      sodiumMg: 41.8,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Whole milk yogurt',
      es: 'Yogur natural entero',
      aliases: ['Whole milk yogurt', 'Yogur natural entero', 'plain yogurt', 'yogur natural'],
    },
  },
  {
    fdcId: 746782,
    usdaDescription: 'Milk, whole, 3.25% milkfat, with added vitamin D',
    per100g: {
      calories: 60,
      proteinG: 3.27,
      carbsG: 4.63,
      fatG: 3.2,
      fiberG: 0,
      sodiumMg: 38,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Whole milk',
      es: 'Leche entera',
      aliases: ['Whole milk', 'Leche entera', 'milk', 'leche'],
    },
  },
  {
    fdcId: 746776,
    usdaDescription: 'Milk, nonfat, fluid, with added vitamin A and vitamin D (fat free or skim)',
    per100g: {
      calories: 34,
      proteinG: 3.43,
      carbsG: 4.92,
      fatG: 0.08,
      fiberG: 0,
      sodiumMg: 41,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Skim milk',
      es: 'Leche descremada',
      aliases: ['Skim milk', 'Leche descremada', 'nonfat milk', 'leche sin grasa'],
    },
  },
  {
    fdcId: 328841,
    usdaDescription: 'Cheese, cottage, lowfat, 2% milkfat',
    per100g: {
      calories: 84,
      proteinG: 11,
      carbsG: 4.31,
      fatG: 2.3,
      fiberG: 0,
      sodiumMg: 321,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Low-fat cottage cheese',
      es: 'Queso cottage bajo en grasa',
      aliases: [
        'Low-fat cottage cheese',
        'Queso cottage bajo en grasa',
        'cottage cheese',
        'queso cottage',
      ],
    },
  },
  {
    fdcId: 329370,
    usdaDescription: 'Cheese, mozzarella, low moisture, part-skim',
    per100g: {
      calories: 298,
      proteinG: 23.7,
      carbsG: 4.44,
      fatG: 20.4,
      fiberG: 0,
      sodiumMg: 699,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Part-skim mozzarella',
      es: 'Mozzarella parcialmente descremada',
      aliases: [
        'Part-skim mozzarella',
        'Mozzarella parcialmente descremada',
        'mozzarella',
        'queso mozzarella',
      ],
    },
  },
  {
    fdcId: 328637,
    usdaDescription: 'Cheese, cheddar',
    per100g: {
      calories: 408,
      proteinG: 23.3,
      carbsG: 2.44,
      fatG: 34,
      fiberG: 0,
      sodiumMg: 654,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Cheddar cheese',
      es: 'Queso cheddar',
      aliases: ['Cheddar cheese', 'Queso cheddar', 'cheddar', 'queso cheddar'],
    },
  },
  {
    fdcId: 325036,
    usdaDescription: 'Cheese, parmesan, grated',
    per100g: {
      calories: 421,
      proteinG: 29.6,
      carbsG: 12.4,
      fatG: 28,
      fiberG: 0,
      sodiumMg: 1750,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Grated parmesan',
      es: 'Queso parmesano rallado',
      aliases: ['Grated parmesan', 'Queso parmesano rallado', 'parmesan', 'parmesano'],
    },
  },
  {
    fdcId: 2346396,
    usdaDescription: 'Oats, whole grain, rolled, old fashioned',
    per100g: {
      calories: 382,
      proteinG: 13.5,
      carbsG: 68.7,
      fatG: 5.89,
      fiberG: 0,
      sodiumMg: 0.668,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Rolled oats',
      es: 'Avena arrollada',
      aliases: ['Rolled oats', 'Avena arrollada', 'oats', 'avena'],
    },
  },
  {
    fdcId: 2512381,
    usdaDescription: 'Rice, white, long grain, unenriched, raw',
    per100g: {
      calories: 359,
      proteinG: 7.04,
      carbsG: 80.3,
      fatG: 1.03,
      fiberG: 0.149,
      sodiumMg: 0.462,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'White rice',
      es: 'Arroz blanco',
      aliases: ['White rice', 'Arroz blanco', 'rice', 'arroz'],
    },
  },
  {
    fdcId: 2512380,
    usdaDescription: 'Rice, brown, long grain, unenriched, raw',
    per100g: {
      calories: 366,
      proteinG: 7.25,
      carbsG: 76.7,
      fatG: 3.31,
      fiberG: 3.02,
      sodiumMg: 0,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Brown rice',
      es: 'Arroz integral',
      aliases: ['Brown rice', 'Arroz integral', 'brown rice', 'arroz integral'],
    },
  },
  {
    fdcId: 2710821,
    usdaDescription: 'Wild rice, dry, raw',
    per100g: {
      calories: 369,
      proteinG: 12.8,
      carbsG: 75.7,
      fatG: 1.7,
      fiberG: 4.26,
      sodiumMg: 1.01,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Wild rice',
      es: 'Arroz salvaje',
      aliases: ['Wild rice', 'Arroz salvaje', 'wild rice', 'arroz salvaje'],
    },
  },
  {
    fdcId: 2346401,
    usdaDescription: 'Potatoes, russet, without skin, raw',
    per100g: {
      calories: 83.4,
      proteinG: 2.27,
      carbsG: 17.8,
      fatG: 0.36,
      fiberG: 0,
      sodiumMg: 2.74,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Russet potato',
      es: 'Papa',
      aliases: ['Russet potato', 'Papa', 'potato', 'papa'],
    },
  },
  {
    fdcId: 2346404,
    usdaDescription: 'Sweet potatoes, orange flesh, without skin, raw',
    per100g: {
      calories: 79,
      proteinG: 1.58,
      carbsG: 17.3,
      fatG: 0.375,
      fiberG: 0,
      sodiumMg: 0,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Orange sweet potato',
      es: 'Batata',
      aliases: ['Orange sweet potato', 'Batata', 'sweet potato', 'camote', 'boniato'],
    },
  },
  {
    fdcId: 2710826,
    usdaDescription: 'Corn, sweet, yellow and white kernels,  fresh, raw',
    per100g: {
      calories: 84.6,
      proteinG: 2.79,
      carbsG: 14.7,
      fatG: 1.63,
      fiberG: 2.43,
      sodiumMg: 0,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Sweet corn',
      es: 'Maíz dulce',
      aliases: ['Sweet corn', 'Maíz dulce', 'corn', 'maiz', 'choclo'],
    },
  },
  {
    fdcId: 2644283,
    usdaDescription: 'Lentils, dry',
    per100g: {
      calories: 360,
      proteinG: 23.6,
      carbsG: 62.2,
      fatG: 1.92,
      fiberG: 0,
      sodiumMg: 0,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Dry lentils',
      es: 'Lentejas secas',
      aliases: ['Dry lentils', 'Lentejas secas', 'lentils', 'lentejas'],
    },
  },
  {
    fdcId: 2644282,
    usdaDescription: 'Chickpeas, (garbanzo beans, bengal gram), dry',
    per100g: {
      calories: 383,
      proteinG: 21.3,
      carbsG: 60.4,
      fatG: 6.27,
      fiberG: 0,
      sodiumMg: 8.78,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Dry chickpeas',
      es: 'Garbanzos secos',
      aliases: ['Dry chickpeas', 'Garbanzos secos', 'chickpeas', 'garbanzos'],
    },
  },
  {
    fdcId: 2644288,
    usdaDescription:
      'Chickpeas (garbanzo beans, bengal gram), canned, sodium added, drained and rinsed',
    per100g: {
      calories: 137,
      proteinG: 7.02,
      carbsG: 20.3,
      fatG: 3.1,
      fiberG: 0,
      sodiumMg: 202,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Canned chickpeas',
      es: 'Garbanzos en lata',
      aliases: ['Canned chickpeas', 'Garbanzos en lata', 'canned chickpeas', 'garbanzos cocidos'],
    },
  },
  {
    fdcId: 2262072,
    usdaDescription: 'Peanut butter, creamy',
    per100g: {
      calories: 632,
      proteinG: 24,
      carbsG: 22.7,
      fatG: 49.4,
      fiberG: 6.32,
      sodiumMg: 221,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Creamy peanut butter',
      es: 'Manteca de maní cremosa',
      aliases: [
        'Creamy peanut butter',
        'Manteca de maní cremosa',
        'peanut butter',
        'mantequilla de mani',
      ],
    },
  },
  {
    fdcId: 2262074,
    usdaDescription: 'Almond butter, creamy',
    per100g: {
      calories: 645,
      proteinG: 20.8,
      carbsG: 21.2,
      fatG: 53,
      fiberG: 9.72,
      sodiumMg: 0.996,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Creamy almond butter',
      es: 'Manteca de almendras',
      aliases: [
        'Creamy almond butter',
        'Manteca de almendras',
        'almond butter',
        'mantequilla de almendras',
      ],
    },
  },
  {
    fdcId: 2346393,
    usdaDescription: 'Nuts, almonds, whole, raw',
    per100g: {
      calories: 626,
      proteinG: 21.5,
      carbsG: 20,
      fatG: 51.1,
      fiberG: 10.8,
      sodiumMg: 0,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Raw almonds',
      es: 'Almendras crudas',
      aliases: ['Raw almonds', 'Almendras crudas', 'almonds', 'almendras'],
    },
  },
  {
    fdcId: 2346394,
    usdaDescription: 'Nuts, walnuts, English, halves, raw',
    per100g: {
      calories: 730,
      proteinG: 14.6,
      carbsG: 10.9,
      fatG: 69.7,
      fiberG: 5.21,
      sodiumMg: 0,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Raw walnuts',
      es: 'Nueces',
      aliases: ['Raw walnuts', 'Nueces', 'walnuts', 'nueces'],
    },
  },
  {
    fdcId: 2710824,
    usdaDescription: 'Avocado, Hass, peeled, raw',
    per100g: {
      calories: 223,
      proteinG: 1.81,
      carbsG: 8.32,
      fatG: 20.3,
      fiberG: 0,
      sodiumMg: 0,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Hass avocado',
      es: 'Palta Hass',
      aliases: ['Hass avocado', 'Palta Hass', 'avocado', 'palta', 'aguacate'],
    },
  },
  {
    fdcId: 747447,
    usdaDescription: 'Broccoli, raw',
    per100g: {
      calories: 31,
      proteinG: 2.57,
      carbsG: 6.27,
      fatG: 0.34,
      fiberG: 2.4,
      sodiumMg: 36,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Raw broccoli',
      es: 'Brócoli crudo',
      aliases: ['Raw broccoli', 'Brócoli crudo', 'broccoli', 'brocoli'],
    },
  },
  {
    fdcId: 2258586,
    usdaDescription: 'Carrots, mature, raw',
    per100g: {
      calories: 48,
      proteinG: 0.941,
      carbsG: 10.3,
      fatG: 0.351,
      fiberG: 3.1,
      sodiumMg: 86.6,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Raw carrot',
      es: 'Zanahoria cruda',
      aliases: ['Raw carrot', 'Zanahoria cruda', 'carrot', 'zanahoria'],
    },
  },
  {
    fdcId: 1999632,
    usdaDescription: 'Spinach, baby',
    per100g: {
      calories: 26.6,
      proteinG: 2.85,
      carbsG: 2.41,
      fatG: 0.619,
      fiberG: 1.56,
      sodiumMg: 111,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Baby spinach',
      es: 'Espinaca baby',
      aliases: ['Baby spinach', 'Espinaca baby', 'spinach', 'espinaca'],
    },
  },
  {
    fdcId: 746769,
    usdaDescription: 'Lettuce, cos or romaine, raw',
    per100g: {
      calories: 17,
      proteinG: 1.24,
      carbsG: 3.24,
      fatG: 0.26,
      fiberG: 1.8,
      sodiumMg: 0,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: false,
    },
    presentation: {
      en: 'Romaine lettuce',
      es: 'Lechuga romana',
      aliases: ['Romaine lettuce', 'Lechuga romana', 'romaine', 'lettuce', 'lechuga'],
    },
  },
  {
    fdcId: 321360,
    usdaDescription: 'Tomatoes, grape, raw',
    per100g: {
      calories: 27,
      proteinG: 0.83,
      carbsG: 5.51,
      fatG: 0.63,
      fiberG: 2.1,
      sodiumMg: 6,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Grape tomato',
      es: 'Tomate uva',
      aliases: ['Grape tomato', 'Tomate uva', 'tomato', 'tomate'],
    },
  },
  {
    fdcId: 790646,
    usdaDescription: 'Onions, yellow, raw',
    per100g: {
      calories: 38,
      proteinG: 0.83,
      carbsG: 8.61,
      fatG: 0.05,
      fiberG: 1.9,
      sodiumMg: 1,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Yellow onion',
      es: 'Cebolla amarilla',
      aliases: ['Yellow onion', 'Cebolla amarilla', 'onion', 'cebolla'],
    },
  },
  {
    fdcId: 1104647,
    usdaDescription: 'Garlic, raw',
    per100g: {
      calories: 143,
      proteinG: 6.62,
      carbsG: 28.2,
      fatG: 0.38,
      fiberG: 2.7,
      sodiumMg: 0,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: false,
    },
    presentation: {
      en: 'Raw garlic',
      es: 'Ajo crudo',
      aliases: ['Raw garlic', 'Ajo crudo', 'garlic', 'ajo'],
    },
  },
  {
    fdcId: 2346406,
    usdaDescription: 'Cucumber, with peel, raw',
    per100g: {
      calories: 15.9,
      proteinG: 0.625,
      carbsG: 2.95,
      fatG: 0.178,
      fiberG: 0,
      sodiumMg: 1.52,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Cucumber with peel',
      es: 'Pepino con cáscara',
      aliases: ['Cucumber with peel', 'Pepino con cáscara', 'cucumber', 'pepino'],
    },
  },
  {
    fdcId: 2258589,
    usdaDescription: 'Peppers, bell, yellow, raw',
    per100g: {
      calories: 30.8,
      proteinG: 0.819,
      carbsG: 6.6,
      fatG: 0.121,
      fiberG: 1.07,
      sodiumMg: 0,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Red bell pepper',
      es: 'Morrón rojo',
      aliases: [
        'Red bell pepper',
        'Morrón rojo',
        'bell pepper',
        'red pepper',
        'pimiento',
        'morron',
      ],
    },
  },
  {
    fdcId: 2346414,
    usdaDescription: 'Applesauce, unsweetened, with added vitamin C',
    per100g: {
      calories: 51.6,
      proteinG: 0.273,
      carbsG: 12.3,
      fatG: 0.162,
      fiberG: 0,
      sodiumMg: 0.504,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Raw blueberries',
      es: 'Arándanos',
      aliases: ['Raw blueberries', 'Arándanos', 'blueberries', 'arandanos'],
    },
  },
  {
    fdcId: 2346409,
    usdaDescription: 'Strawberries, raw',
    per100g: {
      calories: 36.4,
      proteinG: 0.641,
      carbsG: 7.96,
      fatG: 0.22,
      fiberG: 0,
      sodiumMg: 0,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Raw strawberries',
      es: 'Frutillas',
      aliases: ['Raw strawberries', 'Frutillas', 'strawberries', 'fresas'],
    },
  },
  {
    fdcId: 1750341,
    usdaDescription: 'Apples, gala, with skin, raw',
    per100g: {
      calories: 61,
      proteinG: 0.133,
      carbsG: 14.8,
      fatG: 0.15,
      fiberG: 2.11,
      sodiumMg: 0.279,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Gala apple',
      es: 'Manzana Gala',
      aliases: ['Gala apple', 'Manzana Gala', 'apple', 'manzana'],
    },
  },
  {
    fdcId: 1105314,
    usdaDescription: 'Bananas, ripe and slightly ripe, raw',
    per100g: {
      calories: 97,
      proteinG: 0.74,
      carbsG: 23,
      fatG: 0.29,
      fiberG: 1.7,
      sodiumMg: 0,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Ripe banana',
      es: 'Banana madura',
      aliases: ['Ripe banana', 'Banana madura', 'banana', 'platano'],
    },
  },
  {
    fdcId: 746771,
    usdaDescription: 'Oranges, raw, navels',
    per100g: {
      calories: 47,
      proteinG: 0.91,
      carbsG: 11.8,
      fatG: 0.15,
      fiberG: 2,
      sodiumMg: 9,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Navel orange',
      es: 'Naranja',
      aliases: ['Navel orange', 'Naranja', 'orange', 'naranja'],
    },
  },
  {
    fdcId: 2346398,
    usdaDescription: 'Pineapple, raw',
    per100g: {
      calories: 60.1,
      proteinG: 0.461,
      carbsG: 14.1,
      fatG: 0.211,
      fiberG: 0.935,
      sodiumMg: 0,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Raw pineapple',
      es: 'Ananá',
      aliases: ['Raw pineapple', 'Ananá', 'pineapple', 'anana', 'piña'],
    },
  },
  {
    fdcId: 2257045,
    usdaDescription: 'Almond milk, unsweetened, plain, refrigerated',
    per100g: {
      calories: 19.3,
      proteinG: 0.656,
      carbsG: 0.671,
      fatG: 1.56,
      fiberG: 0,
      sodiumMg: 59.2,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Unsweetened almond milk',
      es: 'Leche de almendras sin azúcar',
      aliases: [
        'Unsweetened almond milk',
        'Leche de almendras sin azúcar',
        'almond milk',
        'leche de almendras',
      ],
    },
  },
  {
    fdcId: 1999630,
    usdaDescription: 'Soy milk, unsweetened, plain, shelf stable',
    per100g: {
      calories: 38.5,
      proteinG: 3.55,
      carbsG: 1.29,
      fatG: 2.12,
      fiberG: 0,
      sodiumMg: 34.3,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Unsweetened soy milk',
      es: 'Leche de soja sin azúcar',
      aliases: ['Unsweetened soy milk', 'Leche de soja sin azúcar', 'soy milk', 'leche de soja'],
    },
  },
  {
    fdcId: 2257046,
    usdaDescription: 'Oat milk, unsweetened, plain, refrigerated',
    per100g: {
      calories: 48.3,
      proteinG: 0.797,
      carbsG: 5.1,
      fatG: 2.75,
      fiberG: 0,
      sodiumMg: 42,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Unsweetened oat milk',
      es: 'Leche de avena sin azúcar',
      aliases: ['Unsweetened oat milk', 'Leche de avena sin azúcar', 'oat milk', 'leche de avena'],
    },
  },
  {
    fdcId: 2646171,
    usdaDescription: 'Chicken, thigh, boneless, skinless, raw',
    per100g: {
      calories: 144,
      proteinG: 18.6,
      carbsG: 0,
      fatG: 7.92,
      fiberG: 0,
      sodiumMg: 62.3,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Chicken thigh',
      es: 'Muslo de pollo',
      aliases: ['Chicken thigh', 'Muslo de pollo', 'chicken thigh', 'muslo pollo'],
    },
  },
  {
    fdcId: 2646169,
    usdaDescription: 'Pork, loin, tenderloin, boneless, raw',
    per100g: {
      calories: 119,
      proteinG: 21.6,
      carbsG: 0,
      fatG: 3.9,
      fiberG: 0,
      sodiumMg: 41.4,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Pork tenderloin',
      es: 'Lomo de cerdo',
      aliases: ['Pork tenderloin', 'Lomo de cerdo', 'pork tenderloin', 'cerdo'],
    },
  },
  {
    fdcId: 2644291,
    usdaDescription: 'Peas, green, sweet, canned, sodium added, sugar added, drained and rinsed',
    per100g: {
      calories: 80.1,
      proteinG: 4.73,
      carbsG: 12.7,
      fatG: 1.15,
      fiberG: 0,
      sodiumMg: 207,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Canned green peas',
      es: 'Arvejas en lata',
      aliases: ['Canned green peas', 'Arvejas en lata', 'peas', 'arvejas', 'guisantes'],
    },
  },
  {
    fdcId: 1999629,
    usdaDescription: 'Mushrooms, white button',
    per100g: {
      calories: 31.2,
      proteinG: 2.89,
      carbsG: 4.08,
      fatG: 0.371,
      fiberG: 1.72,
      sodiumMg: 6.44,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'White button mushrooms',
      es: 'Champiñones blancos',
      aliases: ['White button mushrooms', 'Champiñones blancos', 'mushrooms', 'champiñones'],
    },
  },
  {
    fdcId: 2003598,
    usdaDescription: 'Mushroom, portabella',
    per100g: {
      calories: 32.4,
      proteinG: 2.75,
      carbsG: 4.66,
      fatG: 0.312,
      fiberG: 1.88,
      sodiumMg: 5.31,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Portabella mushroom',
      es: 'Hongo portobello',
      aliases: ['Portabella mushroom', 'Hongo portobello', 'portabella', 'portobello'],
    },
  },
  {
    fdcId: 2003601,
    usdaDescription: 'Mushroom, crimini',
    per100g: {
      calories: 30.2,
      proteinG: 3.09,
      carbsG: 4.01,
      fatG: 0.197,
      fiberG: 1.78,
      sodiumMg: 4.57,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: true,
      sodiumMg: true,
    },
    presentation: {
      en: 'Crimini mushroom',
      es: 'Hongo crimini',
      aliases: ['Crimini mushroom', 'Hongo crimini', 'crimini', 'champiñon'],
    },
  },
  {
    fdcId: 2346384,
    usdaDescription: 'Cottage cheese, full fat, large or small curd',
    per100g: {
      calories: 103,
      proteinG: 11.6,
      carbsG: 4.6,
      fatG: 4.22,
      fiberG: 0,
      sodiumMg: 350,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Full-fat cottage cheese',
      es: 'Queso cottage entero',
      aliases: [
        'Full-fat cottage cheese',
        'Queso cottage entero',
        'cottage cheese',
        'queso cottage entero',
      ],
    },
  },
  {
    fdcId: 2259792,
    usdaDescription: 'Buttermilk, low fat',
    per100g: {
      calories: 42.8,
      proteinG: 3.46,
      carbsG: 4.81,
      fatG: 1.08,
      fiberG: 0,
      sodiumMg: 92.5,
    },
    knownNutrients: {
      calories: true,
      proteinG: true,
      carbsG: true,
      fatG: true,
      fiberG: false,
      sodiumMg: true,
    },
    presentation: {
      en: 'Low-fat buttermilk',
      es: 'Buttermilk bajo en grasa',
      aliases: ['Low-fat buttermilk', 'Buttermilk bajo en grasa', 'buttermilk', 'suero de leche'],
    },
  },
] as const;
